# Generated by Django 4.0.6 on 2022-08-15 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0002_books_active_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='copies',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='books',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
