# Generated by Django 4.0.6 on 2022-08-17 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0003_alter_books_copies_alter_books_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
